on:
  workflow_dispatch:
  push:
    branches:
      - staging

name: Auto-Deploy Dev-Build / staging ðŸš€
jobs:
  web-deploy:
    name: Dev-Build Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v2

      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo "Bun installed"

      - name: Add Bun to PATH
        run: echo "${HOME}/.bun/bin" >> $GITHUB_PATH

      - name: Installing packages
        run: bun install

      - name: Install cross-env
        run: bun add cross-env

      - name: Build Project
        run: bun run staging

      - name: Deploying to the server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.HOST }}
          username: ${{ secrets.DEV_USER }}
          password: ${{ secrets.DEV_PASSWORD }}

          local-dir: ./build/
          server-dir: ./2025/${{ secrets.DEV_FOLDER || 'unnamed_project' }}/

          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
